repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.1
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==20.1.0; python_version >= "3.5"']
- repo: https://github.com/asottile/blacken-docs
  rev: v1.7.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
